Repository AY2122S1-CS2103T-F12-1/tp, pull requests merged in 2021-10, with the labels that each got.

#18 docs: update DG product scope
  docs/DeveloperGuide.md
Labels: type.documentation

#21 Update _config.yml
  docs/_config.yml
Labels: type.documentation

#61 Feature: Change theme
  src/main/java/seedu/smartnus/commons/core/theme/DarkTheme.java
  src/main/java/seedu/smartnus/commons/core/theme/LightTheme.java
  src/main/java/seedu/smartnus/commons/core/theme/Theme.java
  src/main/java/seedu/smartnus/logic/Logic.java
  src/main/java/seedu/smartnus/logic/LogicManager.java
  src/main/java/seedu/smartnus/logic/commands/ThemeCommand.java
  src/main/java/seedu/smartnus/logic/parser/ParserUtil.java
  src/main/java/seedu/smartnus/logic/parser/SmartNusParser.java
  src/main/java/seedu/smartnus/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/smartnus/model/Model.java
  src/main/java/seedu/smartnus/model/ModelManager.java
  src/main/java/seedu/smartnus/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/smartnus/model/UserPrefs.java
  src/main/java/seedu/smartnus/ui/MainWindow.java
  src/main/java/seedu/smartnus/ui/UiManager.java
  src/main/resources/view/Fonts.css
  src/main/resources/view/LightExtensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/smartnus/commons/core/theme/ThemeTest.java
  src/test/java/seedu/smartnus/logic/LogicManagerTest.java
  src/test/java/seedu/smartnus/logic/commands/AddCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/AddMcqCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/ThemeCommandTest.java
  src/test/java/seedu/smartnus/logic/parser/SmartNusParserTest.java
  src/test/java/seedu/smartnus/logic/parser/ThemeCommandParserTest.java
Labels: type.enhancement

#68 Add tf sample questions
  src/main/java/seedu/smartnus/model/util/SampleDataUtil.java
Labels: type.enhancement

#76 Update DG with basic parser logic
  docs/DeveloperGuide.md
Labels: type.documentation

#164 fix saq adding duplicate correct attempts stats
  src/main/java/seedu/smartnus/model/question/ShortAnswerQuestion.java
  src/test/java/seedu/smartnus/model/question/ShortAnswerQuestionTest.java
Labels: bug

#162 Fix quiz hyperlinks, standardise title of headers to be imperatives
  docs/UserGuide.md
Labels: type.documentation

#189 Update edit command so it doesn't reset question list
  docs/UserGuide.md
  src/main/java/seedu/smartnus/logic/commands/EditCommand.java
  src/test/java/seedu/smartnus/logic/commands/EditCommandTest.java
Labels: bug

#191 docs: fix findcommand description in ug
  docs/UserGuide.md
Labels: type.documentation

#190 Fix: find command not displaying questions
  src/main/java/seedu/smartnus/logic/commands/CommandUtil.java
  src/main/java/seedu/smartnus/logic/commands/DeleteCommand.java
  src/main/java/seedu/smartnus/logic/commands/FindCommand.java
  src/main/java/seedu/smartnus/logic/commands/ListCommand.java
  src/main/java/seedu/smartnus/logic/commands/StatCommand.java
  src/main/java/seedu/smartnus/logic/parser/ParserUtil.java
  src/test/java/seedu/smartnus/logic/commands/FindCommandTest.java
Labels: bug

#192 Fix user guide url
  src/main/java/seedu/smartnus/ui/HelpWindow.java
Labels: bug

#195 Update version number
  src/main/java/seedu/smartnus/MainApp.java
Labels: bug

#199 Update SAQ docs and error messages
  docs/UserGuide.md
  src/main/java/seedu/smartnus/logic/commands/questions/AddSaqCommand.java
Labels: type.documentation
