Repository AY2122S1-CS2103T-F12-1/tp, pull requests merged in 2021-11, with the labels that each got.

#200 Fix continued validation
  src/main/java/seedu/smartnus/logic/parser/quiz/AnswerMcqCommandParser.java
  src/main/java/seedu/smartnus/logic/parser/quiz/AnswerSaqCommandParser.java
  src/main/java/seedu/smartnus/logic/parser/quiz/AnswerTfqCommandParser.java
  src/main/java/seedu/smartnus/model/quiz/QuizManager.java
  src/test/java/seedu/smartnus/logic/parser/quiz/AnswerMcqCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/quiz/AnswerSaqCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/quiz/AnswerTfqCommandParserTest.java
Labels: type.FunctionalityBug

#194 Fix various UG issues
  docs/UserGuide.md
Labels: type.DocumentationBug

#203 Restructured User Guide
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_layout.scss
Labels: type.documentation

#209 Update FindCommand and documentation
  docs/UserGuide.md
  src/main/java/seedu/smartnus/commons/util/StringUtil.java
  src/main/java/seedu/smartnus/logic/commands/FindCommand.java
  src/main/java/seedu/smartnus/logic/parser/FindCommandParser.java
  src/main/java/seedu/smartnus/model/util/SampleDataUtil.java
  src/test/java/seedu/smartnus/logic/commands/FindCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/quiz/AnswerTfCommandTest.java
  src/test/java/seedu/smartnus/logic/parser/FindCommandParserTest.java
Labels: bug

#208 Sort documentation images into folders
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/about-us/agentum07.png
  docs/images/about-us/aryagiat.png
  docs/images/about-us/cedricongjh.png
  docs/images/about-us/neojxuan.png
  docs/images/about-us/ryanpeh.png
  docs/images/developer-guide/ArchitectureDiagram.png
  docs/images/developer-guide/ArchitectureSequenceDiagram.png
  docs/images/developer-guide/BetterModelClassDiagram.png
  docs/images/developer-guide/CommitActivityDiagram.png
  docs/images/developer-guide/ComponentManagers.png
  docs/images/developer-guide/DeleteSequenceDiagram.png
  docs/images/developer-guide/LogicClassDiagram.png
  docs/images/developer-guide/LogicStorageDIP.png
  docs/images/developer-guide/ModelClassDiagram.png
  docs/images/developer-guide/ParserClasses.png
  docs/images/developer-guide/StorageClassDiagram.png
  docs/images/developer-guide/UiClassDiagram.png
  docs/images/developer-guide/UndoRedoState0.png
  docs/images/developer-guide/UndoRedoState1.png
  docs/images/developer-guide/UndoRedoState2.png
  docs/images/developer-guide/UndoRedoState3.png
  docs/images/developer-guide/UndoRedoState4.png
  docs/images/developer-guide/UndoRedoState5.png
  docs/images/developer-guide/UndoSequenceDiagram.png
  docs/images/johndoe.png
  docs/images/user-guide/UiMainWindow.png
  docs/images/user-guide/findAlexDavidResult.png
  docs/images/user-guide/helpMessage.png
  docs/tutorials/TracingCode.md
Labels: type.documentation

#224 Change TypicalQuestions to proper questions
  src/test/java/seedu/smartnus/logic/LogicManagerTest.java
  src/test/java/seedu/smartnus/logic/commands/CommandTestUtil.java
  src/test/java/seedu/smartnus/logic/commands/EditCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/EditQuestionDescriptorTest.java
  src/test/java/seedu/smartnus/logic/commands/StatCommandTest.java
  src/test/java/seedu/smartnus/logic/parser/AddMcqCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/AddSaqCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/AddTfCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/smartnus/logic/parser/QuizInputParserTest.java
  src/test/java/seedu/smartnus/logic/parser/StatCommandParserTest.java
  src/test/java/seedu/smartnus/model/ModelManagerTest.java
  src/test/java/seedu/smartnus/model/SmartNusTest.java
  src/test/java/seedu/smartnus/model/question/QuestionTest.java
  src/test/java/seedu/smartnus/model/question/UniqueQuestionListTest.java
  src/test/java/seedu/smartnus/model/quiz/QuizTest.java
  src/test/java/seedu/smartnus/storage/JsonAdaptedQuestionTest.java
  src/test/java/seedu/smartnus/storage/JsonSmartNusStorageTest.java
  src/test/java/seedu/smartnus/testutil/TypicalQuestions.java
  src/test/java/seedu/smartnus/testutil/TypicalQuiz.java
Labels: refactor

#226 Fixed all delete command error messages
  docs/UserGuide.md
  src/main/java/seedu/smartnus/commons/core/Messages.java
  src/main/java/seedu/smartnus/logic/commands/DeleteCommand.java
  src/main/java/seedu/smartnus/logic/parser/DeleteCommandParser.java
Labels: type.documentation, type.FunctionalityBug

#225 Fix SAQ keywords validation
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  src/main/java/seedu/smartnus/logic/parser/ParserUtil.java
  src/main/java/seedu/smartnus/model/choice/Choice.java
  src/main/java/seedu/smartnus/model/question/Question.java
  src/main/java/seedu/smartnus/model/question/ShortAnswerQuestion.java
  src/main/java/seedu/smartnus/ui/SaqChoiceGrid.java
  src/test/java/seedu/smartnus/logic/commands/CommandTestUtil.java
  src/test/java/seedu/smartnus/logic/parser/AddSaqCommandParserTest.java
  src/test/java/seedu/smartnus/model/question/ShortAnswerQuestionTest.java
  src/test/java/seedu/smartnus/testutil/QuestionBuilder.java
  src/test/java/seedu/smartnus/testutil/TypicalQuestions.java
Labels: type.FunctionalityBug

#232 Arya PPP
  docs/team/aryagiat.md
Labels: type.documentation

#214 Clearly separate between panels
  docs/DeveloperGuide.md
  docs/diagrams/StatisticClassDiagram.puml
  docs/diagrams/StatisticSequenceDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/smartnus/commons/core/Messages.java
  src/main/java/seedu/smartnus/logic/commands/AddNoteCommand.java
  src/main/java/seedu/smartnus/logic/commands/DeleteCommand.java
  src/main/java/seedu/smartnus/logic/commands/EditCommand.java
  src/main/java/seedu/smartnus/logic/commands/FindCommand.java
  src/main/java/seedu/smartnus/logic/commands/StatCommand.java
  src/main/java/seedu/smartnus/logic/commands/questions/AddQuestionCommand.java
  src/main/java/seedu/smartnus/logic/commands/quiz/QuizCommand.java
  src/main/java/seedu/smartnus/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/smartnus/logic/commands/AddMcqCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/EditCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/FindCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/StatCommandTest.java
  src/test/java/seedu/smartnus/logic/commands/quiz/QuizCommandTest.java
  src/test/java/seedu/smartnus/model/ModelStub.java
  src/test/java/seedu/smartnus/model/ModelStubNotePanel.java
  src/test/java/seedu/smartnus/model/ModelStubTagPanel.java
Labels: priority.high, type.FunctionalityBug

#210 Fix: rephrase index error message to not use technical term
  docs/UserGuide.md
  src/main/java/seedu/smartnus/logic/parser/ParserUtil.java
Labels: type.FunctionalityBug

#236 update documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/team/abhishekgupta.md
  docs/team/johndoe.md
Labels: type.documentation

#241 Update UG styling and DG diagrams
  docs/UserGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/developer-guide/UndoRedoState0.png
  docs/images/developer-guide/UndoRedoState1.png
  docs/images/developer-guide/UndoRedoState2.png
  docs/images/developer-guide/UndoRedoState3.png
  docs/images/developer-guide/UndoRedoState4.png
  docs/images/developer-guide/UndoRedoState5.png
  docs/images/developer-guide/UndoSequenceDiagram.png
Labels: type.DocumentationBug

#243 Abhishek PPP
  docs/team/abhishekgupta.md
Labels: type.documentation

#242 Rerun through DG and update them
  docs/AboutUs.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/NoteClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkHello.png
  docs/images/developer-guide/ArchitectureSequenceDiagram.png
  docs/images/developer-guide/NoteClassDiagram.png
  docs/images/developer-guide/UiClassDiagram.png
  docs/images/remove/$address.png
  docs/images/remove/SafeDeleteConflicts.png
  docs/images/remove/UnsafeDelete.png
  docs/images/remove/UnsafeDeleteOnField.png
  docs/images/tracing/DebuggerStep1.png
  docs/images/tracing/EditCommand.png
  docs/images/tracing/Variables.png
  docs/images/tracing/searchResultsForExecuteMethod.png
  docs/team/aryagiat.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: type.documentation

#255 Fix: Quiz n now uses current question list status
  docs/AboutUs.md
  src/main/java/seedu/smartnus/logic/commands/ExitCommand.java
  src/main/java/seedu/smartnus/logic/commands/quiz/QuizCommand.java
  src/main/java/seedu/smartnus/logic/parser/quiz/QuizCommandParser.java
  src/main/java/seedu/smartnus/model/Model.java
  src/main/java/seedu/smartnus/model/ModelManager.java
  src/main/java/seedu/smartnus/ui/MainWindow.java
  src/main/java/seedu/smartnus/ui/panel/QuestionListPanel.java
  src/test/java/seedu/smartnus/logic/commands/quiz/QuizCommandTest.java
  src/test/java/seedu/smartnus/model/ModelStub.java
  src/test/java/seedu/smartnus/model/ModelStubNotePanel.java
  src/test/java/seedu/smartnus/model/ModelStubTagPanel.java
Labels: priority.high

#270 add manual tests for notes
  docs/DeveloperGuide.md
  docs/images/user-guide/NoteDeletionFailure.PNG
  docs/images/user-guide/SuccessfulNoteDeletion.PNG
  docs/images/user-guide/SuccessfulNoteInAnotherLanguage.PNG
  docs/images/user-guide/UiSuccessfulEnglishNote.PNG
  docs/img.png
Labels: type.documentation
